// <auto-generated />
using System;
using Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250418091925_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Attachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiscussionId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FileSize")
                        .HasColumnType("int");

                    b.Property<string>("ServerFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("AttachmentId");

                    b.HasIndex("DiscussionId");

                    b.HasIndex("TicketId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Application Bug"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Network Issue"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "User Issue"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Discussion", b =>
                {
                    b.Property<int>("DiscussionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscussionId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DiscussionId");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("Discussions");
                });

            modelBuilder.Entity("Domain.Entities.Priority", b =>
                {
                    b.Property<int>("PriorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriorityId"));

                    b.Property<int>("ExpectedDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PriorityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PriorityId");

                    b.ToTable("Priorities");

                    b.HasData(
                        new
                        {
                            PriorityId = 1,
                            ExpectedDays = 14,
                            IsActive = true,
                            PriorityName = "Low"
                        },
                        new
                        {
                            PriorityId = 2,
                            ExpectedDays = 7,
                            IsActive = true,
                            PriorityName = "Medium"
                        },
                        new
                        {
                            PriorityId = 3,
                            ExpectedDays = 1,
                            IsActive = true,
                            PriorityName = "High"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductName = "Product 1"
                        },
                        new
                        {
                            ProductId = 2,
                            ProductName = "Product 2"
                        },
                        new
                        {
                            ProductId = 3,
                            ProductName = "Product 3"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<string>("AssignedToId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ClosedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpectedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("RaisedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RaisedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TicketId");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = 1,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 1,
                            Description = "Description 1",
                            ExpectedDate = new DateTime(2025, 4, 25, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4415),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4365),
                            Status = "NEW",
                            Summary = "Ticket 1"
                        },
                        new
                        {
                            TicketId = 2,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 2,
                            Description = "Description 2",
                            ExpectedDate = new DateTime(2025, 4, 21, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4422),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4421),
                            Status = "OPEN",
                            Summary = "Ticket 2"
                        },
                        new
                        {
                            TicketId = 3,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 3,
                            ClosedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            ClosedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4429),
                            Description = "Description 3",
                            ExpectedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4427),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4425),
                            Status = "CLOSED",
                            Summary = "Ticket 3"
                        },
                        new
                        {
                            TicketId = 4,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 1,
                            Description = "Description 4",
                            ExpectedDate = new DateTime(2025, 4, 25, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4435),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4434),
                            Status = "NEW",
                            Summary = "Ticket 4"
                        },
                        new
                        {
                            TicketId = 5,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 2,
                            Description = "Description 5",
                            ExpectedDate = new DateTime(2025, 4, 21, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4439),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4438),
                            Status = "OPEN",
                            Summary = "Ticket 5"
                        },
                        new
                        {
                            TicketId = 6,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 3,
                            ClosedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            ClosedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4445),
                            Description = "Description 6",
                            ExpectedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4443),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4442),
                            Status = "CLOSED",
                            Summary = "Ticket 6"
                        },
                        new
                        {
                            TicketId = 7,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 1,
                            Description = "Description 7",
                            ExpectedDate = new DateTime(2025, 4, 25, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4450),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4448),
                            Status = "NEW",
                            Summary = "Ticket 7"
                        },
                        new
                        {
                            TicketId = 8,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 2,
                            Description = "Description 8",
                            ExpectedDate = new DateTime(2025, 4, 21, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4454),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4452),
                            Status = "OPEN",
                            Summary = "Ticket 8"
                        },
                        new
                        {
                            TicketId = 9,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 3,
                            ClosedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            ClosedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4460),
                            Description = "Description 9",
                            ExpectedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4458),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4457),
                            Status = "CLOSED",
                            Summary = "Ticket 9"
                        },
                        new
                        {
                            TicketId = 10,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 1,
                            Description = "Description 10",
                            ExpectedDate = new DateTime(2025, 4, 25, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4464),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4463),
                            Status = "NEW",
                            Summary = "Ticket 10"
                        },
                        new
                        {
                            TicketId = 11,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 2,
                            Description = "Description 11",
                            ExpectedDate = new DateTime(2025, 4, 21, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4468),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4467),
                            Status = "OPEN",
                            Summary = "Ticket 11"
                        },
                        new
                        {
                            TicketId = 12,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 3,
                            ClosedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            ClosedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4474),
                            Description = "Description 12",
                            ExpectedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4472),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4471),
                            Status = "CLOSED",
                            Summary = "Ticket 12"
                        },
                        new
                        {
                            TicketId = 13,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 1,
                            Description = "Description 13",
                            ExpectedDate = new DateTime(2025, 4, 25, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4479),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4478),
                            Status = "NEW",
                            Summary = "Ticket 13"
                        },
                        new
                        {
                            TicketId = 14,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 2,
                            Description = "Description 14",
                            ExpectedDate = new DateTime(2025, 4, 21, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4483),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4482),
                            Status = "OPEN",
                            Summary = "Ticket 14"
                        },
                        new
                        {
                            TicketId = 15,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 3,
                            ClosedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            ClosedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4489),
                            Description = "Description 15",
                            ExpectedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4487),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4486),
                            Status = "CLOSED",
                            Summary = "Ticket 15"
                        },
                        new
                        {
                            TicketId = 16,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 1,
                            Description = "Description 16",
                            ExpectedDate = new DateTime(2025, 4, 25, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4493),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4492),
                            Status = "NEW",
                            Summary = "Ticket 16"
                        },
                        new
                        {
                            TicketId = 17,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 2,
                            Description = "Description 17",
                            ExpectedDate = new DateTime(2025, 4, 21, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4497),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4495),
                            Status = "OPEN",
                            Summary = "Ticket 17"
                        },
                        new
                        {
                            TicketId = 18,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 3,
                            ClosedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            ClosedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4503),
                            Description = "Description 18",
                            ExpectedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4501),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4500),
                            Status = "CLOSED",
                            Summary = "Ticket 18"
                        },
                        new
                        {
                            TicketId = 19,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 1,
                            Description = "Description 19",
                            ExpectedDate = new DateTime(2025, 4, 25, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4507),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4506),
                            Status = "NEW",
                            Summary = "Ticket 19"
                        },
                        new
                        {
                            TicketId = 20,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 2,
                            Description = "Description 20",
                            ExpectedDate = new DateTime(2025, 4, 21, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4511),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4510),
                            Status = "OPEN",
                            Summary = "Ticket 20"
                        },
                        new
                        {
                            TicketId = 21,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 3,
                            ClosedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            ClosedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4517),
                            Description = "Description 21",
                            ExpectedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4515),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4514),
                            Status = "CLOSED",
                            Summary = "Ticket 21"
                        },
                        new
                        {
                            TicketId = 22,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 1,
                            Description = "Description 22",
                            ExpectedDate = new DateTime(2025, 4, 25, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4522),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4520),
                            Status = "NEW",
                            Summary = "Ticket 22"
                        },
                        new
                        {
                            TicketId = 23,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 2,
                            Description = "Description 23",
                            ExpectedDate = new DateTime(2025, 4, 21, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4526),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4525),
                            Status = "OPEN",
                            Summary = "Ticket 23"
                        },
                        new
                        {
                            TicketId = 24,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 3,
                            ClosedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            ClosedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4532),
                            Description = "Description 24",
                            ExpectedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4530),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4528),
                            Status = "CLOSED",
                            Summary = "Ticket 24"
                        },
                        new
                        {
                            TicketId = 25,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 1,
                            Description = "Description 25",
                            ExpectedDate = new DateTime(2025, 4, 25, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4535),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4534),
                            Status = "NEW",
                            Summary = "Ticket 25"
                        },
                        new
                        {
                            TicketId = 26,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 2,
                            Description = "Description 26",
                            ExpectedDate = new DateTime(2025, 4, 21, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4539),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4538),
                            Status = "OPEN",
                            Summary = "Ticket 26"
                        },
                        new
                        {
                            TicketId = 27,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 3,
                            ClosedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            ClosedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4546),
                            Description = "Description 27",
                            ExpectedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4544),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4543),
                            Status = "CLOSED",
                            Summary = "Ticket 27"
                        },
                        new
                        {
                            TicketId = 28,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 1,
                            Description = "Description 28",
                            ExpectedDate = new DateTime(2025, 4, 25, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4550),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4548),
                            Status = "NEW",
                            Summary = "Ticket 28"
                        },
                        new
                        {
                            TicketId = 29,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 2,
                            Description = "Description 29",
                            ExpectedDate = new DateTime(2025, 4, 21, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4554),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4553),
                            Status = "OPEN",
                            Summary = "Ticket 29"
                        },
                        new
                        {
                            TicketId = 30,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 3,
                            ClosedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            ClosedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4560),
                            Description = "Description 30",
                            ExpectedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4558),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4556),
                            Status = "CLOSED",
                            Summary = "Ticket 30"
                        },
                        new
                        {
                            TicketId = 31,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 1,
                            Description = "Description 31",
                            ExpectedDate = new DateTime(2025, 4, 25, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4564),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4562),
                            Status = "NEW",
                            Summary = "Ticket 31"
                        },
                        new
                        {
                            TicketId = 32,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 2,
                            Description = "Description 32",
                            ExpectedDate = new DateTime(2025, 4, 21, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4567),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4566),
                            Status = "OPEN",
                            Summary = "Ticket 32"
                        },
                        new
                        {
                            TicketId = 33,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 3,
                            ClosedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            ClosedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4573),
                            Description = "Description 33",
                            ExpectedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4572),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4570),
                            Status = "CLOSED",
                            Summary = "Ticket 33"
                        },
                        new
                        {
                            TicketId = 34,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 1,
                            Description = "Description 34",
                            ExpectedDate = new DateTime(2025, 4, 25, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4607),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4606),
                            Status = "NEW",
                            Summary = "Ticket 34"
                        },
                        new
                        {
                            TicketId = 35,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 2,
                            Description = "Description 35",
                            ExpectedDate = new DateTime(2025, 4, 21, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4612),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4610),
                            Status = "OPEN",
                            Summary = "Ticket 35"
                        },
                        new
                        {
                            TicketId = 36,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 3,
                            ClosedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            ClosedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4618),
                            Description = "Description 36",
                            ExpectedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4616),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4615),
                            Status = "CLOSED",
                            Summary = "Ticket 36"
                        },
                        new
                        {
                            TicketId = 37,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 1,
                            Description = "Description 37",
                            ExpectedDate = new DateTime(2025, 4, 25, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4622),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4620),
                            Status = "NEW",
                            Summary = "Ticket 37"
                        },
                        new
                        {
                            TicketId = 38,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 2,
                            Description = "Description 38",
                            ExpectedDate = new DateTime(2025, 4, 21, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4626),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4625),
                            Status = "OPEN",
                            Summary = "Ticket 38"
                        },
                        new
                        {
                            TicketId = 39,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 3,
                            ClosedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            ClosedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4632),
                            Description = "Description 39",
                            ExpectedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4630),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4629),
                            Status = "CLOSED",
                            Summary = "Ticket 39"
                        },
                        new
                        {
                            TicketId = 40,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 1,
                            Description = "Description 40",
                            ExpectedDate = new DateTime(2025, 4, 25, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4636),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4634),
                            Status = "NEW",
                            Summary = "Ticket 40"
                        },
                        new
                        {
                            TicketId = 41,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 2,
                            Description = "Description 41",
                            ExpectedDate = new DateTime(2025, 4, 21, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4640),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4638),
                            Status = "OPEN",
                            Summary = "Ticket 41"
                        },
                        new
                        {
                            TicketId = 42,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 3,
                            ClosedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            ClosedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4646),
                            Description = "Description 42",
                            ExpectedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4644),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4642),
                            Status = "CLOSED",
                            Summary = "Ticket 42"
                        },
                        new
                        {
                            TicketId = 43,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 1,
                            Description = "Description 43",
                            ExpectedDate = new DateTime(2025, 4, 25, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4650),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4648),
                            Status = "NEW",
                            Summary = "Ticket 43"
                        },
                        new
                        {
                            TicketId = 44,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 2,
                            Description = "Description 44",
                            ExpectedDate = new DateTime(2025, 4, 21, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4654),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4652),
                            Status = "OPEN",
                            Summary = "Ticket 44"
                        },
                        new
                        {
                            TicketId = 45,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 3,
                            ClosedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            ClosedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4660),
                            Description = "Description 45",
                            ExpectedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4658),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4657),
                            Status = "CLOSED",
                            Summary = "Ticket 45"
                        },
                        new
                        {
                            TicketId = 46,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 1,
                            Description = "Description 46",
                            ExpectedDate = new DateTime(2025, 4, 25, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4665),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4664),
                            Status = "NEW",
                            Summary = "Ticket 46"
                        },
                        new
                        {
                            TicketId = 47,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 2,
                            Description = "Description 47",
                            ExpectedDate = new DateTime(2025, 4, 21, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4669),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4668),
                            Status = "OPEN",
                            Summary = "Ticket 47"
                        },
                        new
                        {
                            TicketId = 48,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 3,
                            ClosedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            ClosedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4676),
                            Description = "Description 48",
                            ExpectedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4674),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4672),
                            Status = "CLOSED",
                            Summary = "Ticket 48"
                        },
                        new
                        {
                            TicketId = 49,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 1,
                            Description = "Description 49",
                            ExpectedDate = new DateTime(2025, 4, 25, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4679),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4678),
                            Status = "NEW",
                            Summary = "Ticket 49"
                        },
                        new
                        {
                            TicketId = 50,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 2,
                            Description = "Description 50",
                            ExpectedDate = new DateTime(2025, 4, 21, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4683),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4682),
                            Status = "OPEN",
                            Summary = "Ticket 50"
                        },
                        new
                        {
                            TicketId = 51,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 2,
                            Description = "Description 41",
                            ExpectedDate = new DateTime(2025, 4, 21, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4687),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4686),
                            Status = "OPEN",
                            Summary = "Ticket 41"
                        },
                        new
                        {
                            TicketId = 52,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 3,
                            ClosedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            ClosedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4693),
                            Description = "Description 42",
                            ExpectedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4691),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4690),
                            Status = "CLOSED",
                            Summary = "Ticket 42"
                        },
                        new
                        {
                            TicketId = 53,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 1,
                            Description = "Description 43",
                            ExpectedDate = new DateTime(2025, 4, 25, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4697),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4696),
                            Status = "NEW",
                            Summary = "Ticket 43"
                        },
                        new
                        {
                            TicketId = 54,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 2,
                            Description = "Description 44",
                            ExpectedDate = new DateTime(2025, 4, 21, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4701),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4700),
                            Status = "OPEN",
                            Summary = "Ticket 44"
                        },
                        new
                        {
                            TicketId = 55,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 3,
                            ClosedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            ClosedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4707),
                            Description = "Description 45",
                            ExpectedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4705),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4704),
                            Status = "CLOSED",
                            Summary = "Ticket 45"
                        },
                        new
                        {
                            TicketId = 56,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 1,
                            Description = "Description 46",
                            ExpectedDate = new DateTime(2025, 4, 25, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4710),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4709),
                            Status = "NEW",
                            Summary = "Ticket 46"
                        },
                        new
                        {
                            TicketId = 57,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 2,
                            Description = "Description 47",
                            ExpectedDate = new DateTime(2025, 4, 21, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4714),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4713),
                            Status = "OPEN",
                            Summary = "Ticket 47"
                        },
                        new
                        {
                            TicketId = 58,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 3,
                            ClosedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            ClosedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4720),
                            Description = "Description 48",
                            ExpectedDate = new DateTime(2025, 4, 19, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4718),
                            PriorityId = 3,
                            ProductId = 3,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4717),
                            Status = "CLOSED",
                            Summary = "Ticket 48"
                        },
                        new
                        {
                            TicketId = 59,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 1,
                            Description = "Description 49",
                            ExpectedDate = new DateTime(2025, 4, 25, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4724),
                            PriorityId = 1,
                            ProductId = 1,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4722),
                            Status = "NEW",
                            Summary = "Ticket 49"
                        },
                        new
                        {
                            TicketId = 60,
                            AssignedToId = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            CategoryId = 2,
                            Description = "Description 50",
                            ExpectedDate = new DateTime(2025, 4, 21, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4728),
                            PriorityId = 2,
                            ProductId = 2,
                            RaisedBy = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            RaisedDate = new DateTime(2025, 4, 18, 11, 19, 25, 296, DateTimeKind.Local).AddTicks(4726),
                            Status = "OPEN",
                            Summary = "Ticket 50"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("AccountConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "62f94fe7-0580-42df-969c-4b0f1a2c3d7e",
                            AccessFailedCount = 0,
                            AccountConfirmed = false,
                            ConcurrencyStamp = "24014c0c-04fc-48a2-bf84-2227abc1f9bd",
                            Email = "Test@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TEST@GMAIL.COM",
                            NormalizedUserName = "TEST@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDIYerstHdTH97X6ZhuEOfBxt1jrJlXFBcEAeVsRP+S+y/5pLVza5hCpjc0IHSz4WQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "27b30204-8575-43ce-98d0-000d0c151b57",
                            TwoFactorEnabled = false,
                            UserName = "Test@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Attachment", b =>
                {
                    b.HasOne("Domain.Entities.Discussion", "Discussion")
                        .WithMany("Attachments")
                        .HasForeignKey("DiscussionId");

                    b.HasOne("Domain.Entities.Ticket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discussion");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Domain.Entities.Discussion", b =>
                {
                    b.HasOne("Domain.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Domain.Entities.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Priority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("AssignedTo");

                    b.Navigation("Category");

                    b.Navigation("Priority");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Discussion", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
